### ISSUE TITLE
Other TokenType

### ISSUE THREAD

**Issue by tjherman16** [adshares/adserver#1030]
**Is your feature request related to a problem? Please describe.**
I need to allow my users to trade an asset class similar to ads and also well suited to tokenization.  

**Describe the solution you'd like**
I would like a version of the ad server that can deal with a different asset class other than ads, like collectibles tokens.

**Describe alternatives you've considered**
I'm planning to pay someone to build this for me, that's my alternative.

**Additional context**

**Comment by m-pilarczyk** [comment]
Hi, we are planning to add swapping interface to automatically exchange tokens from ADS to custom ones. But ADS is still required at the base level to send payments between adservers.
