### ISSUE TITLE
MySQL driver not found while trying to deploy

### ISSUE THREAD

**Issue by chrstph-gg** [adshares/adserver#1083]
**Description**

After installing everything via the installer (manually changed the installer script to php7.4, because nothing will work with 7.2 due to composer being unable to stay compatible), I am unable to deploy the installed services, because the sql driver could not be found.

**Expected behavior**
Migration starts

**Error**

`CRITICAL  [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction". Message: "An exception occurred in driver: could not find driver" ["exception" => Doctrine\DBAL\Exception\DriverException^ { …},"command" => "doctrine:migrations:migrate --no-interaction","message" => "An exception occurred in driver: could not find driver"]`

**Environment:**

 - OS name and version: Ubuntu 18.04 x64
 - PHP 7.4 (as mentioned above)

What am I supposed to do now?

**Comment by m-pilarczyk** [comment]
Hi, please check `.env.local` or `.env` file and update a database connection config.
