### ISSUE TITLE
Installer outdated

### ISSUE THREAD

**Issue by vpsinghbaghel** [adshares/adserver#1087]
**Describe the bug**
Installer is completely outdated. Every single setup has lot of issues for packages and versions and also in setup script.
Please update the installer script and packages included in script.

It installs old version of node which is not compatible with adserver. It installs old version of yarn which is also outdated and modules are not compatible.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - OS name and version: [e.g. Ububtu 18.04 x64]

**Additional context**

**Comment by m-pilarczyk** [comment]
Hi, we are preparing an ansible role to install adserver on any hosting. It should be ready within a month. Stay tuned!
