### ISSUE TITLE
Please add for blogger

### ISSUE THREAD

**Issue by saikumar098** [adshares/adserver#1089]
Sir no information has been given from blogger, where is the information given on your ad network
No  ads codes given for blogger how to put ads on blogger 
![Screenshot_2021-12-21-08-51-21-531_com android chrome](https://user-images.githubusercontent.com/90000199/146865568-cc118e3d-3842-4df3-8e7f-9599c82f6f4f.jpg)
Ads code note show  please fix it

**Comment by m-pilarczyk** [comment]
Hi all you need to do is add custom JS and HTML code to your blog: https://stackoverflow.com/questions/6449733/how-can-i-add-javascript-inside-blogger
