### ISSUE TITLE
User Guide to get started

### ISSUE THREAD

**Issue by pateldaivik** [adshares/adserver#1208]
This looks like an awesome project, I am currently working into digital marketing industry and I am interested to look into this open source project but i am not sure where i can get started. I see the installer project to spin up this repo, but it says deprecated. Are there any other steps or documentation/user guide through which i can spin up the adserver locally and also the related repositories to it. 

Any kind of help would be really appreciated. 
Thank you

**Comment by m-pilarczyk** [comment]
Hi, we've just released new installer https://github.com/adshares/adserver/wiki/How-to-start-adserver
