### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by vino-jasuba** [adshares/adserver#301]
Awesome project going on here. However, I can't figure out what the available configuration options are for. Would be great if you added those to your README so that setting up is that much easier. Thanks!

**Comment by PawelPodkalicki** [comment]
Thank You for suggestion. Currently, we are busy preparing demo release of adServer. When we will be ready, we will complete the documentation.

**Comment by salman4k5m** [comment]
Download brave browser $2dollr pardy link👉https://brave.com/iam779

**Comment by m-pilarczyk** [comment]
As of version 2, all configuration options have been moved to the new dashboard - it should help with server configuration.
https://docs.adshares.net/adserver/how-to-start-adserver.html
https://github.com/adshares/adcontroller
