### ISSUE TITLE
bin/init.sh --build --start --migrate leads to DB not connecting

### ISSUE THREAD

**Issue by hprateek43** [adshares/adserver#303]
**When I run bin/init.sh --build --start --migrate I am not able to get the framework running. It times out when migrating to DB**

Expected Behaviour: UI should be up and running

**To Reproduce**
bin/init.sh --build --start --migrate

**Environment (please complete the following information):**

 - MacOS 10.14 Mojave Public beta 3

**Comment by hprateek43** [comment]
=> php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations)

  at /adserver/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /adserver/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /adserver/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.

**Comment by PawelPodkalicki** [comment]
Unfortunately, the `README.md` is outdated. Currently, we are busy preparing demo release of adServer.  When we will finish, documentation will be updated.

By the way, we currently support Ubuntu 16.04, 18.04, because these version can use command line `ads` client.

**Comment by hprateek43** [comment]
Is there any way I can run this locally right now? Will running it on ubuntu help?

**Comment by PawelPodkalicki** [comment]
As I mentioned before, we are focused on demo release and cannot be helpful at this moment. You could try running on Ubuntu. However, you should remember that `adServer` is only one part of Adshares' ecosystem and it uses few other services from our other repositories. Setting whole environment is quite complicated as this moment.

I suggest You to follow our social media to receive updates on project.

- Medium	http://adshar.es/medium
- Twitter	http://adshar.es/twitter
- Facebook	http://adshar.es/FB
- Telegram	http://adshar.es/Telegram
