### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by michaldzwigala** [adshares/adserver#69]
Kroki:
1. Logujemy się na 
L:user3@e11.click
H:useruser
2. Nie ma go w bazie wiec wybieramy "Register"
3. Potwierdzamy maila
4. Logujemy się ponownie (pierwsze poprawne logowanie)
5. Wybieramy rolę "PUBLISHER"
6. Wybieram Logout
7. Ponownie się logujemy - tym razem aplikacja została zawieszona i użytkownik nie został zalogowany do aplikacji

**Comment by yodahack** [comment]
panel fails:
https://github.com/adshares/adpanel/issues/226
