### ISSUE TITLE
ads.txt support

### ISSUE THREAD

**Issue by lenter83** [adshares/adserver#948]
Adshares should allow sites to add it to ads.txt

Proposed format;
`<server ads address>..adshares.net, <publisher uuid>, DIRECT`

Example: 
`0001-00000028-3E05.adshares.net, 85f115636b384744949300571aad2a4f, DIRECT`

First step is to display this info in the Adpanel.
Second step is to actually look for that information in Adpay module

**Comment by PawelPodkalicki** [comment]
Added in version 2.5.0
